openapi: 3.0.2
info:
  title: 'soj'
  version: ''
paths:
  /api/problem/{id}/:
    get:
      summary: get problem detail by id
      operationId: RetrieveProblem
      parameters:
      - name: id
        in: path
        required: true
        description: Id of the problem.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  title:
                    type: string
                    maxLength: 50
                  time_limit:
                    type: integer
                    maximum: 2147483647
                    minimum: -2147483648
                    description: In ms
                  memory_limit:
                    type: integer
                    maximum: 2147483647
                    minimum: -2147483648
                    description: In KB
                  description:
                    type: string
                  sample_inputs:
                    type: array
                    items:
                      type: string
                    description: one item one test case
                  sample_outputs:
                    type: array
                    items:
                      type: string
                    description: one item one test case
                  note:
                    type: string
          description: ''
    delete:
      summary: delete problem by id
      operationId: DestroyProblem
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this problem.
        schema:
          type: string
      responses:
        '204':
          description: 'successfully deleted'
  /api/problems/:
    get:
      summary: get problem list, the page size is currently 50
      operationId: listProblems
      parameters:
        - name: page
          required: false
          in: query
          description: A page number within the paginated result set.
          schema:
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                  previous:
                    type: string
                    nullable: true
                  results:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                          readOnly: true
                        title:
                          type: string
                          maxLength: 50
                      required:
                        - title
          description: ''
  /api/submission/{id}/:
    get:
      summary: get submission detail by id
      operationId: RetrieveSubmission
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this submission.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  verdict:
                    type: string
                    readOnly: true
                  memory:
                    type: integer
                    maximum: 2147483647
                    minimum: -2147483648
                    description: In KB
                  time:
                    type: integer
                    maximum: 2147483647
                    minimum: -2147483648
                    description: In ms
                  submit_time:
                    type: string
                    format: date-time
                    readOnly: true
                  code:
                    type: string
                  lang:
                    type: string
                  outputs:
                    type: array
                    description: one item one test case
                    items:
                      type: string
          description: ''
  /api/submissions/:
    get:
      summary: get submission list, the page size is currently 50
      operationId: listSubmissions
      parameters:
        - name: page
          required: false
          in: query
          description: A page number within the paginated result set.
          schema:
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                  previous:
                    type: string
                    nullable: true
                  results:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                          readOnly: true
                        problem_id:
                          type: string
                          readOnly: true
                        user:
                          type: string
                          readOnly: true
                        verdict:
                          type: string
                          readOnly: true
                        submit_time:
                          type: string
                          format: date-time
                          readOnly: true
                        time:
                          type: integer
                          maximum: 2147483647
                          minimum: -2147483648
                          description: In ms
                        memory:
                          type: integer
                          maximum: 2147483647
                          minimum: -2147483648
                          description: In KB
          description: ''
  /api/submission/:
    post:
      summary: submit code for a problem
      operationId: CreateSubmissionPost
      parameters: []
      requestBody:
        description: parameters needed
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                pid:
                  type: integer
                  description: the id of the problem
                code:
                  type: string
                  description: code
                lang:
                  type: string
                  description: language, one of attribute names of LanguageEnum
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  submission_id:
                    type: integer
                    description: the id of this submission
          description: ''
  /api/judge/result/:
    post:
      summary: used for judger
      operationId: Createjudge_finished
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/user/login/:
    post:
      operationId: user_login
      parameters: []
      requestBody:
        description: parameters needed
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                username:
                  type: string
                password:
                  type: string
                keep:
                  type: boolean
                  description: true if keep the login status
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
        '404':
          content:
            application/json:
              schema:
                properties:
                  detail:
                    type: string
          description: 'wrong username or password'
  /api/user/logout/:
    post:
      operationId: user_logout
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
